# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

require 'cucumber/rails'
require 'capybara/poltergeist'


require 'capybara/cucumber'


Capybara.configure do |config|
  # Don't start rails
  #config.run_server = false
  # Set capybara's driver. Use your own favorite
  #config.default_driver = :webkit
  config.default_driver = :selenium
  # Make all requests to the Ember app
  config.app_host = 'http://localhost:4200'
end

# Capybara.register_driver :chrome do |app|
#
#   profile = Selenium::WebDriver::Chrome::Profile.new
#
#   Capybara::Selenium::Driver.new(app, profile: profile, :browser => :chrome)
# end
#
# Capybara.configure do |config|
#   config.app_host = 'http://localhost:4200'
#   config.default_driver = (ENV['BROWSER'] || :chrome).to_sym
# end


# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { :except => [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('~@no-txn', '~@selenium', '~@culerity', '~@celerity', '~@javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
#Cucumber::Rails::Database.javascript_strategy = :truncation